version: '3.7'

services:
  animals-db:
    container_name: animals-postgres-db
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - animals-db-volume:/data/postgres
    networks:
      - animals-network
    environment:
      - POSTGRES_DB=animals-db
      - PGDATA=/data/postgres
  animals-api:
    container_name: animals-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - animals-network
    build: 
      context: .
    depends_on:
      - animals-db
    
volumes:
  animals-db-volume:

networks:
  animals-network:
    driver: bridge